In [17]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from Column import *
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud, STOPWORDS

### 📍 Reading [**Dataset**](https://www.kaggle.com/datasets/gpreda/bbc-news/data)

In [18]:
df = pd.read_csv("Dataset/bbc_news.csv")

In [19]:
df.head()

,title,pubDate,guid,link,description
0,Ukraine: Angry Zelensky vows to punish Russian...,"Mon, 07 Mar 2022 08:01:56 GMT",https://www.bbc.co.uk/news/world-europe-60638042,https://www.bbc.co.uk/news/world-europe-606380...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Sun, 06 Mar 2022 22:49:58 GMT",https://www.bbc.co.uk/news/world-europe-60641873,https://www.bbc.co.uk/news/world-europe-606418...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',"Mon, 07 Mar 2022 00:14:42 GMT",https://www.bbc.co.uk/news/business-60623941,https://www.bbc.co.uk/news/business-60623941?a...,One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,"Mon, 07 Mar 2022 00:05:40 GMT",https://www.bbc.co.uk/news/uk-60579079,https://www.bbc.co.uk/news/uk-60579079?at_medi...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,"Mon, 07 Mar 2022 08:15:53 GMT",https://www.bbc.co.uk/news/business-60642786,https://www.bbc.co.uk/news/business-60642786?a...,Consumers are feeling the impact of higher ene...

### 🚩 Add title & Description in Single Column

In [20]:
df["text"] = df["title"] + " " + df["description"]

### ❌ Remove All columns except `text` Column

In [21]:
df = df.drop(columns=df.columns[:-1])

In [22]:
df.shape

(42115, 1)

### 🟢 Check if there is null values and Duplicates

In [25]:
df.isnull().sum()

text    0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(2004)

In [27]:
df.drop_duplicates(inplace=True)

### 🛠 Text Preprocessing 

> - **Column Class:** is used for update **`CleanedText Column`** without repeating Block of Code

In [28]:
df["CleanedText"] = df["text"].apply(lambda e: e.lower())

In [29]:
text = column(Dataset=df,Column_name="CleanedText")

In [30]:
text.Update(func=lambda e: e.lower())
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,ukraine: angry zelensky vows to punish russian...
1,War in Ukraine: Taking cover in a town under a...,war in ukraine: taking cover in a town under a...
2,Ukraine war 'catastrophic for global food' One...,ukraine war 'catastrophic for global food' one...
3,Manchester Arena bombing: Saffie Roussos's par...,manchester arena bombing: saffie roussos's par...
4,Ukraine conflict: Oil price soars to highest l...,ukraine conflict: oil price soars to highest l...
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,highlights: wales make history in dublin watch...
42111,Gang jailed over £200m of cocaine in banana bo...,gang jailed over £200m of cocaine in banana bo...
42112,Scottish Budget presents huge challenges for S...,scottish budget presents huge challenges for s...
42113,Celebrations as Wales make history qualifying ...,celebrations as wales make history qualifying ...
42114,School tells Muslim girls it’s ‘not safe’ for ...,school tells muslim girls it’s ‘not safe’ for ...

### 📍 Removing Any Single Letter

In [32]:
text.Update(func=lambda e:re.sub(pattern=r"\b[a-zA-Z]{1}\b",repl=" ",string=e))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,ukraine: angry zelensky vows to punish russian...
1,War in Ukraine: Taking cover in a town under a...,war in ukraine: taking cover in town under a...
2,Ukraine war 'catastrophic for global food' One...,ukraine war 'catastrophic for global food' one...
3,Manchester Arena bombing: Saffie Roussos's par...,manchester arena bombing: saffie roussos' par...
4,Ukraine conflict: Oil price soars to highest l...,ukraine conflict: oil price soars to highest l...
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,highlights: wales make history in dublin watch...
42111,Gang jailed over £200m of cocaine in banana bo...,gang jailed over £200m of cocaine in banana bo...
42112,Scottish Budget presents huge challenges for S...,scottish budget presents huge challenges for s...
42113,Celebrations as Wales make history qualifying ...,celebrations as wales make history qualifying ...
42114,School tells Muslim girls it’s ‘not safe’ for ...,school tells muslim girls it’ ‘not safe’ for ...

### 📍 Tokenizing

In [33]:
text.Update(func=lambda e:word_tokenize(text=e))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,"[ukraine, :, angry, zelensky, vows, to, punish..."
1,War in Ukraine: Taking cover in a town under a...,"[war, in, ukraine, :, taking, cover, in, town,..."
2,Ukraine war 'catastrophic for global food' One...,"[ukraine, war, 'catastrophic, for, global, foo..."
3,Manchester Arena bombing: Saffie Roussos's par...,"[manchester, arena, bombing, :, saffie, rousso..."
4,Ukraine conflict: Oil price soars to highest l...,"[ukraine, conflict, :, oil, price, soars, to, ..."
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,"[highlights, :, wales, make, history, in, dubl..."
42111,Gang jailed over £200m of cocaine in banana bo...,"[gang, jailed, over, £200m, of, cocaine, in, b..."
42112,Scottish Budget presents huge challenges for S...,"[scottish, budget, presents, huge, challenges,..."
42113,Celebrations as Wales make history qualifying ...,"[celebrations, as, wales, make, history, quali..."
42114,School tells Muslim girls it’s ‘not safe’ for ...,"[school, tells, muslim, girls, it, ’, ‘, not, ..."

### 📍 Removing **Stop Words**

In [34]:
en_stopwords = stopwords.words("english")

def Remove_stopwords(words:list[str]):
    return [word for word in words if word not in en_stopwords]

In [35]:
text.Update(func=lambda x:Remove_stopwords(x))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,"[ukraine, :, angry, zelensky, vows, punish, ru..."
1,War in Ukraine: Taking cover in a town under a...,"[war, ukraine, :, taking, cover, town, attack,..."
2,Ukraine war 'catastrophic for global food' One...,"[ukraine, war, 'catastrophic, global, food, ',..."
3,Manchester Arena bombing: Saffie Roussos's par...,"[manchester, arena, bombing, :, saffie, rousso..."
4,Ukraine conflict: Oil price soars to highest l...,"[ukraine, conflict, :, oil, price, soars, high..."
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,"[highlights, :, wales, make, history, dublin, ..."
42111,Gang jailed over £200m of cocaine in banana bo...,"[gang, jailed, £200m, cocaine, banana, boxes, ..."
42112,Scottish Budget presents huge challenges for S...,"[scottish, budget, presents, huge, challenges,..."
42113,Celebrations as Wales make history qualifying ...,"[celebrations, wales, make, history, qualifyin..."
42114,School tells Muslim girls it’s ‘not safe’ for ...,"[school, tells, muslim, girls, ’, ‘, safe, ’, ..."

### 📍 Lemmatization Words

In [36]:
lemma = WordNetLemmatizer()

def lemmatize(Words:list[str]):
    return [lemma.lemmatize(word=word,pos="v") for word in Words]

In [37]:
text.Update(func=lambda e:lemmatize(e))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,"[ukraine, :, angry, zelensky, vow, punish, rus..."
1,War in Ukraine: Taking cover in a town under a...,"[war, ukraine, :, take, cover, town, attack, j..."
2,Ukraine war 'catastrophic for global food' One...,"[ukraine, war, 'catastrophic, global, food, ',..."
3,Manchester Arena bombing: Saffie Roussos's par...,"[manchester, arena, bomb, :, saffie, roussos, ..."
4,Ukraine conflict: Oil price soars to highest l...,"[ukraine, conflict, :, oil, price, soar, highe..."
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,"[highlight, :, wales, make, history, dublin, w..."
42111,Gang jailed over £200m of cocaine in banana bo...,"[gang, jail, £200m, cocaine, banana, box, two,..."
42112,Scottish Budget presents huge challenges for S...,"[scottish, budget, present, huge, challenge, s..."
42113,Celebrations as Wales make history qualifying ...,"[celebrations, wales, make, history, qualify, ..."
42114,School tells Muslim girls it’s ‘not safe’ for ...,"[school, tell, muslim, girls, ’, ‘, safe, ’, t..."

### 📍 Trans List to String

In [38]:
def to_String(Words:list[str]):
    return " ".join(Words)

In [39]:
text.Update(func=lambda x:to_String(x))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,ukraine : angry zelensky vow punish russian at...
1,War in Ukraine: Taking cover in a town under a...,war ukraine : take cover town attack jeremy bo...
2,Ukraine war 'catastrophic for global food' One...,ukraine war 'catastrophic global food ' one wo...
3,Manchester Arena bombing: Saffie Roussos's par...,manchester arena bomb : saffie roussos ' paren...
4,Ukraine conflict: Oil price soars to highest l...,ukraine conflict : oil price soar highest leve...
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,highlight : wales make history dublin watch hi...
42111,Gang jailed over £200m of cocaine in banana bo...,gang jail £200m cocaine banana box two tonnes ...
42112,Scottish Budget presents huge challenges for S...,scottish budget present huge challenge snp fin...
42113,Celebrations as Wales make history qualifying ...,celebrations wales make history qualify euros ...
42114,School tells Muslim girls it’s ‘not safe’ for ...,school tell muslim girls ’ ‘ safe ’ three chil...

### 📍 Removing any Punctuation

In [40]:
text.Update(func=lambda e:re.sub(pattern=r"[^a-zA-Z]",repl=" ",string=e))
df

,text,CleanedText
0,Ukraine: Angry Zelensky vows to punish Russian...,ukraine angry zelensky vow punish russian at...
1,War in Ukraine: Taking cover in a town under a...,war ukraine take cover town attack jeremy bo...
2,Ukraine war 'catastrophic for global food' One...,ukraine war catastrophic global food one wo...
3,Manchester Arena bombing: Saffie Roussos's par...,manchester arena bomb saffie roussos paren...
4,Ukraine conflict: Oil price soars to highest l...,ukraine conflict oil price soar highest leve...
...,...,...
42110,Highlights: Wales make history in Dublin Watch...,highlight wales make history dublin watch hi...
42111,Gang jailed over £200m of cocaine in banana bo...,gang jail m cocaine banana box two tonnes ...
42112,Scottish Budget presents huge challenges for S...,scottish budget present huge challenge snp fin...
42113,Celebrations as Wales make history qualifying ...,celebrations wales make history qualify euros ...
42114,School tells Muslim girls it’s ‘not safe’ for ...,school tell muslim girls safe three chil...

## 🟢 From Here We Build Model

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation, NMF
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report ,f1_score

---

<h1 align="center">✅ The End of NoteBook</h1>


---